-- delete from PuntosInteres
-- DBCC CHECKIDENT ('PuntosInteres', RESEED, 0); 
-- PARA REINICIAR CONTADOR DE IDS EN CASO HAYA Q EJECUTAR DE NUEVO
use ISSMap;
go
insert into Categorias values ('Ores')
insert into Categorias values ('Herbs')
insert into Categorias values ('Bones')
insert into Categorias values ('Eggs')

INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Iron Ore', 1 , 'Ore that can be smelted into metal and used for many different purposes.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Machalite Ore', 1 , 'Ore that''s more difficult to procure than Iron Ore. Produces fine metal.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Dragonite Ore', 1 , 'An ore that yields metal superior to that of Machalite. Invaluable for making durable armor.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Carbalite Ore', 1 , 'Ore obtained from mining outcrops. Still under research, but known to yield highly pure metal.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Fucium Ore', 1 , 'Ore obtained from the Elder''s Recess. A mysterious metal, capable of fusing nearly any two materials together.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Aquacore Ore', 1 , 'A valuable mineral used to create charms. Gives off a vibrant glow that mirrors the ocean.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Spiritcore Ore', 1 , 'A valuable mineral used to create charms. Gives off a warm, sunny glow.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Dreamcore Ore', 1 , 'A valuable mineral used to create charms. Gives off a blazing glow reminiscent of a bonfire.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Dragoncore Ore', 1 , 'A valuable mineral used to create charms. Gives off a mysterious glow that grants the holder sagely wisdom.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Loc Lac Ore', 1 , 'An Old World import. Beautiful, but not suitable for crafting. (Trade-in Item)');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Eltalite Ore', 1 , 'Ore obtained from mining outcrops. This transcendent ore refines into metal even stronger than carbalite.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Shadowcore Ore', 1 , 'A valuable mineral used to create charms. Its shine somehow saps the light away from its surroundings.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Phantomcore Ore', 1 , 'A valuable mineral used to create charms. Its otherworldy shimmering speaks to the power it contains.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Bathycite Ore', 1 , 'Ore from Coral Highlands. Formed by millennia of pressure acting upon the bones of ancient organisms.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Meldspar Ore', 1 , 'Ore often found in the Rotten Vale. Malleable but strong, it is broadly used in creating alloys for crafting.');

INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Fire Herb', 2 , 'A wondrous, flammable plant. Useful for crafting explosives.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Flowfern', 2 , 'This plant''s leaves store a great amount of water. A component for making Water Ammo.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Snow Herb', 2 , 'A plant that radiates ice-cold air. Use in combinations to create freeze ammo.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Sleep Herb', 2 , 'A plant containing sleeping agents. Used to craft tranquilizers.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Ivy', 2 , 'A lightweight and extremely strong plant. Used to make nets for pitfall traps.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Gloamgrass Bud', 2 , 'A plant with healing properties. Combine it with a Godbug to bring out its full potency.');

INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Steel Egg', 3 , 'An egg of glittering steel. Valuable and rare, but of no use to a hunter. (Trade-in Item)');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Silver Egg', 3 , 'An egg of glittering silver. Valuable and rare, but of no use to a hunter. (Trade-in Item)');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Golden Egg', 3 , 'An egg of glittering gold. Super valuable and rare, but of no use to a hunter. (Trade-in Item)');

INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Sturdy Bone', 4 , 'A bone used as crafting material. Can be found in bonepiles in the Coral Highlands and Rotten Vale.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Quality Bone', 4 , 'A bone used as crafting material. Its ease of use and hardness allow it to be shaped into better gear.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Ancient Bone', 4 , 'A bone used as crafting material. Can be found in bonepiles in the Ancient Forest. Its size evokes a certain primal quality.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Boulder Bone', 4 , 'A bone used as crafting material. Can be found in bonepiles in the Wildspire Waste. Its size evokes a certain primal quality.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Coral Bone', 4 , 'A bone used as crafting material. Can be found in bonepiles in the Coral Highlands. Its size evokes a certain primal quality.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Warped Bone', 4 , 'A bone used as crafting material. Can be found in bonepiles in the Rotten Vale. Its size evokes a certain primal quality.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Brutal Bone', 4 , 'A bone used as crafting material. Can be found in bonepiles in the Elder''s Recess. Its size evokes a certain primal quality.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Dragonbone Relic', 4 , 'A high quality material found in bone piles. The only remains left of a species of dragon now lost to time.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Monster Bone S', 4 , 'A material found in bonepiles. Indispensable for both hunting and daily life.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Monster Bone M', 4 , 'Bone obtained from large monsters. Strong yet flexible, it''s as reliable as steel or wood.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Monster Bone L', 4 , 'Bone obtained from large monsters. Hard to work with due to its size, but vital when crafting larger items.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Monster Bone+', 4 , 'Bone obtained from large monsters. Hard to obtain, but vital for crafting powerful equipment.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Monster Keenbone', 4 , 'Bone obtained from high rank large monsters. It has a razor-sharp tip that retains its strength after forging.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Monster Hardbone', 4 , 'Precious bone obtained from high rank large monsters. Their rarity makes them highly sought after.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Elder Dragon Bone', 4 , 'A bone from an elder dragon. It exudes the great majesty of the beast that bore it.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Anjanath Nosebone', 4 , 'Anjanath material. Obtained by breaking its head. Unusual and difficult to handle.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Anjanath Nosebone+', 4 , 'Rare Anjanath material. Obtained by breaking its head. Unusual and difficult to handle.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Wyvern Bonemass', 4 , 'Radobaan material. Obtained by collecting rare drops. Highly dense, used for many purposes.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Behemoth Bone', 4 , 'Rare Behemoth material. Bone so absurdly strong that it can even knock out legendary heroes.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Dragonbone Artifact', 4 , 'A very rare bone from bonepiles. Evidence of an unknown elder dragon that once ruled the land.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Monster Slogbone', 4 , 'Bone obtained from large master rank monsters. Far heavier than its outward appearance would suggest.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Monster Solidbone', 4 , 'Bone obtained from large master rank monsters. Sturdy enough to withstand even the most ferocious of impacts.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Frozen Bone', 4 , 'A bone found in bonepiles in the Hoarfrost Reach. Tempered by years of the tundra''s unrelenting cold.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Monster Toughbone', 4 , 'Bone obtained from large master rank monsters. It emits a potent aura of near-limitless potential.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Thick Bone', 4 , 'Very rare bone uses as crafting material. While laborious to work, it yields results like no other.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Ancient Cursed Bone', 4 , 'Rare ancient leshen material. A bone entangled in countless magical branches.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Cursed Bone', 4 , 'Rare material. The bone of a creature that fell prey to a leshen''s cunning cruelty.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Heavy Fulgur Anjanath Nosebone', 4 , 'Very rare Fulgur Anjanath material. Obtained by breaking its head. Has a unique composition.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Heavy Anjanath Nosebone', 4 , 'Very rare Anjanath material. Obtained by breaking its head. Used in select gear.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Large Wyvern Bonemass', 4 , 'Very rare Radobaan material. Obtained by collecting rare drops. Highly dense, used for many purposes.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Large Elder Dragon Bone', 4 , 'Material from master rank elder dragons. Equal parts austere and wild, it seems untouched by time.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Elder Dragonvein Bone', 4 , 'Bone obtained from elder dragons in the Guiding Lands. More imposing for having absored earthen energy.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Elder Spiritvein Bone', 4 , 'Bone obtained from tempered monsters in the Guiding Lands. Proof of their status as true masters of the land.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Guiding Forest Dragonbone', 4 , 'Bone obtained in the Guiding Lands'' forest region. Traces of a bygone overlord, drawn by an unknown force.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Guiding Volcanic Dragonbone', 4 , 'Bone obtained in the Guiding Lands'' volcanic region. Traces of a bygone overlord, drawn by an unknown force.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Guiding Coral Dragonbone', 4 , 'Bone obtained in the Guiding Lands'' coral region. Traces of a bygone overlord, drawn by an unknown force.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Guiding Rotted Dragonbone', 4 , 'Bone obtained in the Guiding Lands'' rotted region. Traces of a bygone overlord, drawn by an unknown force.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Guiding Wasteland Dragonbone', 4 , 'Bone obtained in the Guiding Lands'' wildspire region. Traces of a bygone overlord, drawn by an unknown force.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Dragonvein Solidbone', 4 , 'Bone obtained from large monsters in the Guiding Lands. Strong as steel after absorbing earthen energy.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Spiritvein Solidbone', 4 , 'Bone obtained from tempered monsters in the Guiding Lands. Drew in earthen energy to slake its endless thrist.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Slumbering Greatbone', 4 , 'Bone obtained in the Guiding Lands'' forest region. Its curious form suggests untold potential.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Dragonscorched Wildbone', 4 , 'Bone obtained in the Guiding Lands'' volcanic region. Its curious form suggests untold potential.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Vibrant Crimsonbone', 4 , 'Bone obtained in the Guiding Lands'' coral region. Its curious form suggests untold potential.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Afflicted Frenzybone', 4 , 'Bone obtained in the Guiding Lands'' rotted region. Its curious form suggests untold potential.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Tempered Cragbone', 4 , 'Bone obtained in the Guiding Lands'' wildspire region. Its curious form suggests untold potential.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Fierce Dragonvein Bone', 4 , 'Bone obtained from large monsters in the Guiding Lands. Visibly stronger for having absorbed earthen energy.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Heavy Dragonvein Bone', 4 , 'Bone obtained from large monsters in the Guiding Lands. Notably heavier for having absorbed earthen energy.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Spiritvein Slogbone', 4 , 'Bone obtained from tempered monsters in the Guiding Lands. Imbued with the same power as a streamstone.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Mossy Greatbone', 4 , 'Bone obtained in the Guiding Lands'' forest region. Subterranean energy has altered its material properties.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Woodland Greatbone', 4 , 'Bone obtained in the Guiding Lands'' forest region. Weathered as it is, its weight attests to its power.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Simmering Wildbone', 4 , 'Bone obtained in the Guiding Lands'' volcanic region. Subterranean energy has altered its material properties.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Volcanic Wildbone', 4 , 'Bone obtained in the Guiding Lands'' volcanic region. Weathered as it is, its weight attests to its power.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Coral Crimsonbone', 4 , 'Bone obtained in the Guiding Lands'' coral region. Weathered as it is, its weight attests to its power.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Vivid Crimsonbone', 4 , 'Bone obtained in the Guiding Lands'' coral region. Subterranean energy has altered its material properties.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Effluvial Frenzybone', 4 , 'Bone obtained in the Guiding Lands'' rotted region. Weathered as it is, its weight attests to its power.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Malformed Frenzybone', 4 , 'Bone obtained in the Guiding Lands'' rotted region. Subterranean energy has altered its material properties.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Wasteland Cragbone', 4 , 'Bone obtained in the Guiding Lands'' wildspire region. Weathered as it is, its weight attests to its power.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Weathered Cragbone', 4 , 'Bone obtained in the Guiding Lands'' wildspire region. Subterranean energy has altered its material properties.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Hoary Icebone', 4 , 'Bone obtained in the Guiding Lands'' tundra region. Subterranean energy has altered its material properties.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Tundra Icebone', 4 , 'Bone obtained in the Guiding Lands'' tundra region. Weathered as it is, its weight attests to its power.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Everfrost Icebone', 4 , 'Bone obtained in the Guiding Lands'' tundra region. Its curious form suggests untold potential.');
INSERT INTO PuntosInteres (nombre, categoryId, descripcion) VALUES ('Guiding Tundra Dragonbone', 4 , 'Bone obtained in the Guiding Lands'' tundra region. Traces of a bygone overlord, drawn by an unknown force.');


select * from Coordenadas

INSERT INTO Coordenadas (puntoId, x, y) VALUES (1, 76.773, 50.682);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (1, 73.971, 31.553);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (1, 28.086, 6.953);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (2, 71.469, 24.409);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (2, 30.632, 65.953);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (2, 87.869, 9.831);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (3, 6.632, 57.089);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (3, 39.44, 64.869);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (3, 4.305, 55.307);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (3, 90.853, 57.057);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (4, 5.393, 85.333);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (4, 4.993, 2.04);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (5, 39.918, 95.235);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (5, 25.503, 2.815);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (5, 46.205, 78.83);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (5, 37.546, 9.02);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (9, 74.178, 23.53);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (9, 71.171, 45.7);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (9, 22.706, 74.808);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (10, 84.809, 25.68);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (10, 72.566, 53.179);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (10, 73.012, 27.026);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (11, 12.899, 1.445);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (12, 21.204, 95.251);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (12, 9.015, 15.504);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (13, 7.068, 36.312);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (13, 55.334, 12.212);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (13, 17.992, 37.514);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (13, 7.496, 63.021);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (15, 26.217, 22.929);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (17, 4.241, 20.474);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (17, 44.793, 38.423);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (17, 52.722, 46.09);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (18, 83.711, 41.329);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (18, 71.529, 84.732);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (18, 15.754, 4.02);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (19, 38.767, 16.779);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (19, 43.17, 38.367);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (19, 73.155, 82.597);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (19, 29.537, 89.752);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (20, 56.922, 91.721);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (20, 31.775, 6.633);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (20, 61.311, 49.659);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (21, 41.449, 93.448);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (21, 50.054, 92.53);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (21, 49.429, 85.432);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (22, 91.359, 42.551);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (22, 81.117, 45.099);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (22, 73.527, 66.405);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (24, 33.337, 60.905);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (24, 22.776, 60.844);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (24, 20.058, 4.486);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (24, 41.395, 17.972);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (25, 12.419, 91.9);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (25, 35.301, 83.176);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (25, 2.394, 23.573);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (25, 7.787, 53.975);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (26, 29.988, 7.57);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (26, 72.757, 98.012);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (27, 50.441, 27.946);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (28, 77.089, 47.831);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (28, 26.516, 62.349);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (28, 17.024, 70.259);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (29, 28.441, 32.538);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (29, 98.953, 38.035);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (29, 53.001, 34.001);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (29, 35.527, 93.96);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (30, 89.71, 99.091);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (30, 10.824, 92.585);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (30, 5.049, 75.155);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (30, 27.627, 64.948);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (31, 53.222, 73.9);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (31, 86.791, 91.833);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (31, 1.462, 89.971);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (31, 33.569, 34.6);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (32, 64.799, 9.41);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (32, 69.914, 87.316);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (32, 67.667, 6.701);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (34, 26.642, 51.736);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (35, 14.399, 41.659);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (35, 20.413, 65.041);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (35, 60.54, 79.995);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (35, 74.225, 37.306);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (36, 6.065, 4.363);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (37, 82.32, 11.464);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (38, 15.485, 94.838);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (39, 32.223, 66.181);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (39, 50.963, 90.007);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (39, 32.618, 55.99);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (40, 38.361, 40.545);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (40, 54.61, 83.343);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (40, 50.456, 84.685);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (42, 51.946, 28.338);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (43, 23.134, 96.424);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (43, 55.43, 49.77);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (43, 61.404, 10.396);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (44, 85.387, 35.515);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (44, 60.767, 25.993);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (45, 47.612, 44.272);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (45, 8.576, 48.724);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (45, 30.467, 82.282);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (45, 35.91, 66.12);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (46, 23.528, 12.785);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (46, 47.387, 80.068);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (46, 19.988, 82.484);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (47, 9.806, 43.928);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (47, 18.552, 4.447);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (47, 26.149, 93.379);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (47, 52.974, 37.567);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (48, 93.284, 59.332);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (48, 78.588, 61.876);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (48, 6.702, 44.066);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (50, 31.4, 25.201);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (50, 8.839, 17.076);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (50, 46.32, 38.133);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (51, 30.82, 22.053);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (52, 3.416, 97.501);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (52, 3.85, 40.99);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (52, 27.328, 53.701);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (52, 88.707, 81.84);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (53, 89.644, 52.148);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (53, 61.988, 84.386);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (54, 33.579, 95.695);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (54, 32.898, 84.209);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (55, 89.414, 88.48);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (55, 71.149, 26.544);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (55, 5.354, 18.474);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (58, 49.156, 9.435);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (59, 51.847, 10.782);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (59, 48.158, 37.278);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (59, 37.725, 66.04);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (59, 56.402, 58.301);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (60, 32.165, 9.035);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (60, 85.738, 79.586);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (60, 24.892, 60.193);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (60, 74.797, 31.741);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (61, 22.364, 87.7);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (61, 86.541, 58.256);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (61, 86.949, 53.669);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (62, 12.543, 44.966);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (62, 13.387, 55.313);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (63, 24.073, 59.572);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (63, 26.054, 56.015);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (65, 54.647, 11.799);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (67, 63.232, 79.284);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (67, 90.186, 72.784);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (67, 23.707, 70.268);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (68, 33.955, 73.038);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (68, 74.513, 85.828);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (68, 29.569, 8.165);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (70, 45.578, 12.278);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (70, 16.05, 15.395);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (70, 99.735, 66.997);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (70, 22.27, 64.986);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (71, 89.508, 52.935);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (71, 76.363, 67.311);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (71, 51.646, 44.556);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (71, 23.248, 62.471);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (72, 4.529, 89.51);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (72, 6.616, 25.028);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (73, 85.007, 89.175);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (73, 17.972, 48.275);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (74, 7.319, 12.611);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (74, 37.689, 41.595);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (76, 90.679, 34.389);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (77, 35.024, 56.603);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (78, 48.533, 58.082);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (78, 80.835, 69.404);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (78, 2.248, 88.061);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (79, 92.693, 87.926);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (79, 91.396, 51.909);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (81, 60.459, 42.715);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (81, 96.942, 28.115);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (82, 21.317, 87.106);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (82, 88.647, 23.821);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (83, 85.622, 38.352);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (83, 57.918, 19.82);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (84, 2.421, 16.35);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (84, 4.775, 8.986);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (84, 44.92, 14.265);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (85, 81.843, 79.504);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (85, 88.223, 38.709);
INSERT INTO Coordenadas (puntoId, x, y) VALUES (85, 26.549, 18.296);
